source = "C:\\Users\\User\\DiffMoM.jl\\data\\sonnet_validation\\artwork_native_3hcgXi\\native_32_10000000000.son"
engine_version = "18.53-Lite (64-bit Windows) on X202605221330 local."
ended_utc = "2026-10-03T15:05:45.043"
response_nports = 2
julia_version = "1.13.1"
process_success = true
native_subsections = [308]
deembedded = false
em = "C:\\Program Files\\Sonnet Software\\18.53\\bin\\em.exe"
actual_cell_counts = [32, 32]
started_utc = "2026-10-03T15:05:44.631"
source_sha256 = "08c4c96885c0adab53b7c50d700a00d1bbf29d3bdb8e6c60cfd4515dec2986c5"
command = "setenv(`'C:\\Program Files\\Sonnet Software\\18.53\\bin\\em.exe' -v 'C:\\Users\\User\\DiffMoM.jl\\data\\sonnet_validation\\artwork_native_3hcgXi\\native_32_10000000000\\native_32_10000000000.son'`; dir=\"C:\\\\Users\\\\User\\\\DiffMoM.jl\\\\data\\\\sonnet_validation\\\\artwork_native_3hcgXi\\\\native_32_10000000000\")"
box_halfcell_counts = [64, 64]

[dependency_sha256]
