source = "C:\\Users\\User\\DiffMoM.jl\\data\\sonnet_validation\\artwork_native_3hcgXi\\native_64_10000000000.son"
engine_version = "18.53-Lite (64-bit Windows) on X202605221330 local."
ended_utc = "2026-10-03T15:05:54.083"
response_nports = 2
julia_version = "1.13.1"
process_success = true
native_subsections = [664]
deembedded = false
em = "C:\\Program Files\\Sonnet Software\\18.53\\bin\\em.exe"
actual_cell_counts = [64, 64]
started_utc = "2026-10-03T15:05:53.257"
source_sha256 = "5355036b37506eaa884dbd82783b80a0b1217eebf6fdab2f5afcd96f8dcfc84a"
command = "setenv(`'C:\\Program Files\\Sonnet Software\\18.53\\bin\\em.exe' -v 'C:\\Users\\User\\DiffMoM.jl\\data\\sonnet_validation\\artwork_native_3hcgXi\\native_64_10000000000\\native_64_10000000000.son'`; dir=\"C:\\\\Users\\\\User\\\\DiffMoM.jl\\\\data\\\\sonnet_validation\\\\artwork_native_3hcgXi\\\\native_64_10000000000\")"
box_halfcell_counts = [128, 128]

[dependency_sha256]
