source = "C:\\Users\\User\\DiffMoM.jl\\data\\sonnet_validation\\artwork_native_3hcgXi\\native_16_1000000000.son"
engine_version = "18.53-Lite (64-bit Windows) on X202605221330 local."
ended_utc = "2026-10-03T15:05:37.041"
response_nports = 2
julia_version = "1.13.1"
process_success = true
native_subsections = [126]
deembedded = false
em = "C:\\Program Files\\Sonnet Software\\18.53\\bin\\em.exe"
actual_cell_counts = [16, 16]
started_utc = "2026-10-03T15:05:36.581"
source_sha256 = "ac882ee718050cf369fbd37fe29220e551b6e9bdb76cb2aa0b6e8a8394cc3411"
command = "setenv(`'C:\\Program Files\\Sonnet Software\\18.53\\bin\\em.exe' -v 'C:\\Users\\User\\DiffMoM.jl\\data\\sonnet_validation\\artwork_native_3hcgXi\\native_16_1000000000\\native_16_1000000000.son'`; dir=\"C:\\\\Users\\\\User\\\\DiffMoM.jl\\\\data\\\\sonnet_validation\\\\artwork_native_3hcgXi\\\\native_16_1000000000\")"
box_halfcell_counts = [32, 32]

[dependency_sha256]
